# Generated by Django 4.1.1 on 2023-04-15 20:47

from django.db import migrations

from apps.menu.models import Menu


def add_default_menu(apps, *args, **kwargs):
    main_menu, _ = Menu.objects.get_or_create(
        title='Main Menu',
    )

    categories, _ = Menu.objects.get_or_create(
        title='Categories',
        defaults={
            'parent': main_menu,
        },
    )

    for title in ('Vegetables', 'Fruits', 'Nuts'):
        Menu.objects.get_or_create(
            title=title,
            defaults={
                'parent': categories,
            },
        )


def remove_default_menu(apps, *args, **kwargs):
    Menu.objects.filter(title='Main Menu').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_menu, remove_default_menu)
    ]
